#!/usr/bin/env bash
# Read /etc/passwd file line by line
while IFS=':' read -r username _ userid _ _ homedir _; do
  echo "Username: $username"
  echo "User ID: $userid"
  echo "Home Directory: $homedir"
  echo "-------------------------"
done < /etc/passwd
