#!/usr/bin/env bash

# Read the /etc/passwd file line by line
while IFS=':' read -r username password userid groupid comment homedir shell; do
  # Format and display the output as per the requirements
  echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $comment"
done < /etc/passwd

