#!/usr/bin/env bash
# This script displays "Best School" 10 times, and for the 9th iteration, it also displays "Hi".

for i in {1..10}
do
  if [ $i -eq 9 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
done
