#!/usr/bin/env bash
# This script prints "Best School" 10 times, but on the 9th iteration, it also prints "Hi"

n=1
while [ "$n" -le 10 ]; do
  if [ "$n" -eq 9 ]; then
    echo -e "Best School\nHi"
  else
    echo "Best School"
  fi
  n=$((n + 1))
done
