#!/usr/bin/env bash
#initialize a counter variable
i=1

while [ $i -le 20 ]; do
  echo "$i"  # Print the current number
  case $i in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  i=$((i + 1))  # Increment the counter
done

