#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

hour=0

while [ $hour -le 12 ]; do
  echo "Hour: $hour"  # Print the current hour
  minute=1
  while [ $minute -le 59 ]; do
    echo "$minute"  # Print each minute on a new line
    minute=$((minute + 1))
  done
  hour=$((hour + 1))
done
